### get driver of the day
GET http://localhost:3000/fantaformula1/driver-of-day/2023/3

### get fastest lap
GET http://localhost:3000/fantaformula1/fastest-lap/2023/1


### get race number
GET http://localhost:3000/fantaformula1/total-race-number/2019


### get race number
GET http://localhost:3000/fantaformula1/quali-to-race/2023/12
